# Generated by Django 4.0 on 2022-07-29 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0029_alter_order_order_data_alter_order_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.DateField(default=datetime.date(2022, 7, 29)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 29, 19, 29, 2, 778675)),
        ),
    ]
